(function(){var n,aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);
function da(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
da("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;aa(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});da("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var p=this||self;function ea(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"}function q(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}function fa(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function r(a,b,c){r=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?fa:ha;return r.apply(null,arguments)}
function t(a,b){function c(){}c.prototype=b.prototype;a.v=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.S=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};var v;var ia=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ja=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function ka(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function la(a,b,c){for(var d in a)b.call(c,a[d],d,a)}var ma="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function na(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ma.length;f++)c=ma[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var oa=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function pa(a,b){la(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:qa.hasOwnProperty(d)?a.setAttribute(qa[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})}var qa={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function ra(a,b,c){function d(h){h&&b.appendChild(typeof h==="string"?a.createTextNode(h):h)}for(var e=2;e<c.length;e++){var f=c[e];if(!ea(f)||q(f)&&f.nodeType>0)d(f);else{a:{if(f&&typeof f.length=="number"){if(q(f)){var g=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){g=typeof f.item=="function";break a}}g=!1}ja(g?ka(f):f,d)}}}function w(a){for(var b;b=a.firstChild;)a.removeChild(b)}function x(a){return a.contentDocument||a.contentWindow.document}
function y(a){this.h=a||p.document||document}y.prototype.g=function(a,b,c){var d=this.h,e=arguments,f=e[1];var g=String(e[0]);g=String(g);d.contentType==="application/xhtml+xml"&&(g=g.toLowerCase());g=d.createElement(g);f&&(typeof f==="string"?g.className=f:Array.isArray(f)?g.className=f.join(" "):pa(g,f));e.length>2&&ra(d,g,e);return g};function sa(a,b){a.appendChild(b)};function z(){this.i=this.i;this.j=this.j}z.prototype.i=!1;z.prototype.dispose=function(){this.i||(this.i=!0,this.h())};z.prototype[Symbol.dispose]=function(){this.dispose()};z.prototype.h=function(){if(this.j)for(;this.j.length;)this.j.shift()()};function A(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1}A.prototype.h=function(){this.defaultPrevented=!0};var ta=function(){if(!p.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};p.addEventListener("test",c,b);p.removeEventListener("test",c,b)}catch(d){}return a}();function B(a,b){A.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.I=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&
(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;
this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.I=a;a.defaultPrevented&&B.v.h.call(this)}}t(B,A);B.prototype.h=function(){B.v.h.call(this);var a=this.I;a.preventDefault?a.preventDefault():a.returnValue=!1};var C="closure_listenable_"+(Math.random()*1E6|0);var ua=0;function va(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.D=e;this.key=++ua;this.s=this.C=!1}function D(a){a.s=!0;a.listener=null;a.proxy=null;a.src=null;a.D=null};function E(a){this.src=a;this.g={};this.h=0}E.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var g=F(a,b,d,e);g>-1?(b=a[g],c||(b.C=!1)):(b=new va(b,this.src,f,!!d,e),b.C=c,a.push(b));return b};function G(a,b){var c=b.type;if(c in a.g){var d=a.g[c],e=ia(d,b),f;(f=e>=0)&&Array.prototype.splice.call(d,e,1);f&&(D(b),a.g[c].length==0&&(delete a.g[c],a.h--))}}
function F(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.s&&f.listener==b&&f.capture==!!c&&f.D==d)return e}return-1};var H="closure_lm_"+(Math.random()*1E6|0),I={},wa=0;function J(a,b,c,d,e){if(d&&d.once)return K(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)J(a,b[f],c,d,e);return null}c=L(c);return a&&a[C]?a.g.add(String(b),c,!1,q(d)?!!d.capture:!!d,e):xa(a,b,c,!1,d,e)}
function xa(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=q(e)?!!e.capture:!!e,h=M(a);h||(a[H]=h=new E(a));c=h.add(b,c,d,g,f);if(c.proxy)return c;d=ya();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)ta||(e=g),e===void 0&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(za(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");wa++;return c}
function ya(){function a(c){return b.call(a.src,a.listener,c)}var b=Aa;return a}function K(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)K(a,b[f],c,d,e);return null}c=L(c);return a&&a[C]?a.g.add(String(b),c,!0,q(d)?!!d.capture:!!d,e):xa(a,b,c,!0,d,e)}
function Ba(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Ba(a,b[f],c,d,e);else(d=q(d)?!!d.capture:!!d,c=L(c),a&&a[C])?(a=a.g,b=String(b).toString(),b in a.g&&(f=a.g[b],c=F(f,c,d,e),c>-1&&(D(f[c]),Array.prototype.splice.call(f,c,1),f.length==0&&(delete a.g[b],a.h--)))):a&&(a=M(a))&&(b=a.g[b.toString()],a=-1,b&&(a=F(b,c,d,e)),(c=a>-1?b[a]:null)&&N(c))}
function N(a){if(typeof a!=="number"&&a&&!a.s){var b=a.src;if(b&&b[C])G(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(za(c),d):b.addListener&&b.removeListener&&b.removeListener(d);wa--;(c=M(b))?(G(c,a),c.h==0&&(c.src=null,b[H]=null)):D(a)}}}function za(a){return a in I?I[a]:I[a]="on"+a}function Aa(a,b){if(a.s)a=!0;else{b=new B(b,this);var c=a.listener,d=a.D||a.src;a.C&&N(a);a=c.call(d,b)}return a}
function M(a){a=a[H];return a instanceof E?a:null}var O="__closure_events_fn_"+(Math.random()*1E9>>>0);function L(a){if(typeof a==="function")return a;a[O]||(a[O]=function(b){return a.handleEvent(b)});return a[O]};function P(a){z.call(this);this.l=a;this.g={}}t(P,z);var Ca=[];function Q(a,b,c,d){Array.isArray(c)||(c&&(Ca[0]=c.toString()),c=Ca);for(var e=0;e<c.length;e++){var f=J(b,c[e],d||a.handleEvent,!1,a.l||a);if(!f)break;a.g[f.key]=f}return a}function Da(a){la(a.g,function(b,c){this.g.hasOwnProperty(c)&&N(b)},a);a.g={}}P.prototype.h=function(){P.v.h.call(this);Da(this)};P.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Ea(a,b,c){this.A=c;this.G=this.l=null;this.g=1;this.u=a?new y(a.nodeType==9?a:a.ownerDocument||a.document):v||(v=new y);this.B=new P(this);a=this.u;c=a.g("DIV",{className:"switcherOuter",style:"left:0px;top:0px;width:100%;height:100%;"});b.appendChild(c);this.M=c;b=c.offsetWidth-13-2;this.m=a.g("DIV",{className:"switcherContent",style:"left:0px;top:0;width:"+(b-7)+"px;height:80%;"},a.g("TABLE","switcherTable",a.g("TBODY",null,this.J=a.g("TR"))));c.appendChild(this.m);this.i=a.g("DIV",{className:"switcherArrows",
style:"left:"+b+"px;top:0;width:13px;height:50%;"},a.g("B",null,">"));c.appendChild(this.i);this.h=a.g("DIV",{className:"switcherArrows",style:"left:"+b+"px;top:"+c.offsetHeight/2+"px;width:13px;height:50%;"},a.g("B",null,"<"));c.appendChild(this.h);Q(Q(Q(Q(Q(Q(this.B,this.h,"mouseover",this.P),this.i,"mouseover",this.R),this.h,"mouseout",this.N),this.i,"mouseout",this.O),this.h,"mousedown",this.K),this.i,"mousedown",this.K);this.j=0;this.o=null}
function Fa(a,b){var c=a.J.cells.length,d=a.J;d.insertCell(c);var e=d.cells[c];w(e);e.appendChild(a.u.h.createTextNode(String(b.name)));e.item=b;e=d.cells[c];e.className="switcherItem";b.initialSheet&&a.H(b,e,!1);Q(a.B,e,"click",r(a.H,a,b,e,!0));return e}n=Ea.prototype;n.H=function(a,b,c){a!=this.l&&(this.l!=null&&(this.G.className="switcherItem"),this.l=a,this.G=b,b.className="switcherItemActive",b=this.A,b!=null&&b(a,c))};n.L=function(){this.m.scrollLeft+=1*this.g*this.j};
n.P=function(){this.g=1;this.j=-1;this.o=window.setInterval(r(this.L,this),10)};n.R=function(){this.j=this.g=1;this.o=window.setInterval(r(this.L,this),10)};n.N=function(){window.clearInterval(this.o);this.j=0};n.O=function(){window.clearInterval(this.o);this.j=0};n.K=function(){this.g<4?this.g++:this.g=1};n.cleanup=function(){this.A=null};function R(){z.call(this);this.g=new E(this);this.G=this;this.o=null}t(R,z);R.prototype[C]=!0;R.prototype.removeEventListener=function(a,b,c,d){Ba(this,a,b,c,d)};R.prototype.h=function(){R.v.h.call(this);if(this.g){var a=this.g,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,D(d[e]);delete a.g[c];a.h--}}this.o=null};
function S(a,b,c,d){b=a.g.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.s&&g.capture==c){var h=g.listener,m=g.D||g.src;g.C&&G(a.g,g);e=h.call(m,d)!==!1&&e}}return e&&!d.defaultPrevented};function T(a,b){R.call(this);this.F=a;this.B=!!b;this.A=Ga(this);this.A||(this.l=J(this.F,"load",this.u,!1,this),this.m=window.setInterval(r(this.u,this),100))}t(T,R);T.prototype.l=null;function Ha(a){a.m&&(window.clearInterval(a.m),a.m=null)}T.prototype.h=function(){delete this.F;Ha(this);N(this.l);T.v.h.call(this)};function Ga(a){var b=!1;try{var c=x(a.F).body;b=a.B?!!c&&!!c.firstChild:!!c}catch(d){}return b}
T.prototype.u=function(){if(Ga(this)){Ha(this);N(this.l);this.l=null;this.A=!0;var a=this.o;if(a){var b=[];for(var c=1;a;a=a.o)b.push(a),++c}a=this.G;c="ifload";var d=c.type||c;if(typeof c==="string")c=new A(c,a);else if(c instanceof A)c.target=c.target||a;else{var e=c;c=new A(d,a);na(c,e)}e=!0;var f;if(b)for(f=b.length-1;f>=0;f--){var g=c.g=b[f];e=S(g,d,!0,c)&&e}g=c.g=a;e=S(g,d,!0,c)&&e;e=S(g,d,!1,c)&&e;if(b)for(f=0;f<b.length;f++)g=c.g=b[f],e=S(g,d,!1,c)&&e}};function U(a,b,c,d,e,f,g,h){var m=this;this.h=a?new y(a.nodeType==9?a:a.ownerDocument||a.document):v||(v=new y);this.o=h;this.g=this.j=null;var l=this.h;f=l.g("TABLE",{style:"position:relative;left:"+c+"px;top:"+d+"px;width:"+e+";height:"+f+";",cellpadding:0,cellspacing:0},c=l.g("TBODY",null,l.g("TR",null,l.g("TD",null,e=l.g("DIV",{style:"left:0px;top:0px;width:100%;height:100%;overflow:auto"}))),l.g("TR",null,d=l.g("TD",{style:"height:26px;background-color:#eee"}))));b.appendChild(f);this.i=e;this.l=
a=new Ea(a,d,function(k,u){k=r(m.m,m,k,u);if(typeof k!=="function")if(k&&typeof k.handleEvent=="function")k=r(k.handleEvent,k);else throw Error("Invalid listener argument");Number(20)>2147483647||p.setTimeout(k,20)});h&&(h=l.g("DIV","element-link","\u00a0"),sa(c,l.g("TR",null,l.g("TD","element-link-container",h))),J(h,"click",function(){var k=window;var u=oa.test("http://www.google.com/webelements/")?"http://www.google.com/webelements/":void 0;u!==void 0&&k.open(u,void 0,void 0)}));if(g.length){l=
null;for(h=0;h<g.length;h++)b=Fa(a,g[h]),h==0&&(l=b);a.l==null&&a.H(g[0],l,!1)}J(this.h.h.defaultView,"message",function(k){k=k.I;var u=k.origin,X=u.length-11;X>=0&&u.indexOf(".google.com",X)==X&&k.data=="SendKeyboardEvents"&&(m.j=k.origin,V(m,m.h.h),m.g&&V(m,x(m.g)))})}
U.prototype.m=function(a,b){var c=this,d=a.pageUrl,e=this.i;w(e);this.g=null;d=this.h.g("IFRAME",{id:"pageswitcher-content",style:"display: block; width: 100%; height:100%;",frameBorder:"0",marginHeight:"0",marginWidth:"0",src:d});var f=new T(d,!0);K(f,"ifload",function(g){g=g.target;c.g=g.F;g.dispose();c.j&&c.g&&V(c,x(c.g))});e.appendChild(d);b&&a.gid!==void 0&&(window.location.hash="#gid="+a.gid)};
function V(a,b){J(b,["keydown","keyup","keypress"],function(c){if(a.j){var d=a.h.h.defaultView.parent;d&&d.postMessage&&d.postMessage(JSON.stringify({type:c.type,ctrlKey:c.ctrlKey,altKey:c.altKey,shiftKey:c.shiftKey,metaKey:c.metaKey,keyCode:c.keyCode}),a.j)}})}U.prototype.resize=function(a,b){var c=this.i.style;c.width=a+"px";c.height=b-26-(this.o?24:0)+"px";a=this.l;b=a.M.offsetWidth-13-2;a.m.style.width=b-7+"px";a.i.style.left=b+"px";a.h.style.left=b+"px"};
U.prototype.cleanup=function(){this.l.cleanup();this.l=null;w(this.i);this.i=null};function Ia(a,b,c,d,e,f,g,h,m){return new U(b,c,d,e,f,g,h,m)}for(var W=["_getWGTPageSwitcher"],Y=p,Z;W.length&&(Z=W.shift());)W.length||Ia===void 0?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Ia;}).call(this);
